### ISSUE TITLE
Action TestKits don't support using gRPC Clients?

### ISSUE THREAD

**Issue by reid-spencer** [lightbend/kalix-jvm-sdk#696] opened 2021-11-10 19:27 UTC
I am following the documentation on "Calling other services" and "Implementing Actions". I have a GatewayAction that is acting as a controller over the other akka serverless services. I tried to create a tenant entity like this:

```scala
class GatewayServiceAction(creationContext: ActionCreationContext) extends AbstractGatewayServiceAction {
  /** Handler for "createTenant". */
  override def createTenant(tenantConfiguration: TenantConfiguration): Action.Effect[TenantInfo] = {
    val tenantService = actionContext.getGrpcClient(classOf[TenantService],"tenants")
    val id = UUID.randomUUID().toString
    val info = TenantInfo(Identifier(id),tenantConfiguration)
    val result = tenantService.configureTenant(info)
    effects.asyncReply(result)
  }
}
```
and I wrote a little test Spec for it like this:
```scala
class GatewayServiceActionSpec extends AnyWordSpec with ScalaFutures with Matchers {
  "GatewayServiceAction" should {
    "create a tenant" in {
      val testKit = GatewayServiceActionTestKit(new GatewayServiceAction(_))
      val command = TenantConfiguration(displayName = Name("foo")
      val reply = testKit.createTenant(command).reply
      reply.tenantId.value must(not(be(empty)))
      println("TenantId: " + reply.tenantId.value)
      reply.config.displayName must be("foo")
    }
  }
}
```
Running this test spec yielded this:

> java.lang.UnsupportedOperationException: Testing logic using a gRPC client is not possible with the testkit

Why is it not possible? Or should that say "not implemented"?

In any event, I do not understand what is wrong with this approach so I don't have a course of action to try here. Can you nudge me in the right direction?

**Comment by johanandren** [comment] 2021-11-10 20:48
Yeah, the testkit is for unit testing only, tests that interact with other Akka Serverless or external services (or components) can't be written using it. In the long run we'll want to provide some way to mock or fake other services in unit tests, but that is not in place yet.

The only way to do it currently is to write an integration test instead. That's only half the solution though, you will also have to make sure there is a service that can be found for the host name used. Not entirely sure how easy that path is right now if the other service is another Akka Serverless service identified only its deployed name (so not resolvable from the test environment, but you would probably not want to call your production service from a test anyway, right?).

BTW, in the next SDK version, soon to be released, we have greatly improved cross component interactions, so actions calling entities in the same Akka Serverless service. Those will can be tested out of the box with an integration test.

**Comment by reid-spencer** [comment] 2021-11-10 22:16
Got it. I'll just wait for the next release to test Actions → Service.  Thanks for the explanation.

**Comment by efgpinto** [comment] 2022-11-04 23:28
I believe this is a duplicate of [this](https://github.com/lightbend/kalix-jvm-sdk/issues/984) which was fixed some months ago anyway and is supported now with the MockRegistry.

**Closed by efgpinto** 2022-11-04 23:28 UTC
